### ISSUE TITLE
Add to NPM for use in PhoneGap Build?

### ISSUE THREAD

**Issue by baroquedub** [mesmotronic/cordova-plugin-fullscreen#10]
Any chance of making this available on NPM? I use PhoneGap Build and would love to be able to use this plugin.

Many thanks

**Comment by neilrackett** [comment]
I'll see what changes we need to make to [add it to plugman](http://docs.build.phonegap.com/en_US/developer_contributing_plugins.md.html) and let you know!

(I assume that's what you mean?)

**Comment by baroquedub** [comment]
Hi Neil, 

Apologies I guess I might mean plugman too?. Just going by a recommendation on the PhoneGap community forums ( http://community.phonegap.com/nitobi/topics/completely-hiding-soft-keys-in-android-build ) I did a quick check on Google and found this http://phonegap.com/blog/2015/05/26/npm-plugins-available/ so assumed that it would make sense to a plugin developer. 

I guess I just want to be able to add it to my manifest.xml in the usual format for 3rd party plugins. e.g. 
	<gap:plugin name="org.apache.cordova.device-orientation" version="0.3.1" />
	<gap:plugin name="net.yoik.cordova.plugins.screenorientation" version="1.3.1" />

Many thanks indeed

**Comment by neilrackett** [comment]
[This plugin is now available via NPM](https://www.npmjs.com/package/cordova-plugin-fullscreen)
