### ISSUE TITLE
plugin in not working

### ISSUE THREAD

**Issue by vinodhum** [mesmotronic/cordova-plugin-fullscreen#12]
Hi 
I installed plugin using cordova plugin add https://github.com/mesmotronic/cordova-fullscreen-plugin.git
and it was installed successfully I can see the plugin in the plugin dir

I copied the example file and ran the example using phonegap developer app  on htc m8
but nothing happens, it more annoying because phonegap doesn't   throw any error  or success log

can somebody help me to verify that plugin is installed correctly and what am i missing for it not to work.

other plugins works fine except this one 

Thank you

**Comment by robtoll** [comment]
Hello,

I have the same issue. I've tried the old and new versions of the fullscreen plugin, but nothing happens when I run the sample code, and any subsequent code doesn't run at all.

All of the other plugins (that I've tried so far) work for me. I'm using VirtualBox for testing the app on Android, and have tried different versions of Android, with no luck.

Thanks

**Comment by robtoll** [comment]
Still no luck, but have found this
https://github.com/apache/cordova-plugin-statusbar
Seems to do the trick

**Comment by neilrackett** [comment]
My understanding is that the PhoneGap developer app only supports a limited number of the most common plugins, so you will need to do a full build to test your app with the plugin.

**Comment by neilrackett** [comment]
To use the example, you may need to run `cordova plugin rm cordova-plugin-fullscreen` then `cordova plugin add cordova-plugin-fullscreen`, because the plugin is not included in the `example` folder of the repo.

**Comment by robtoll** [comment]
Thanks for the response. I've tried different versions, removing and re-adding but it doesn't work using a basic setup with "phonegap serve". I think I may be confusing phonegap plugins with other non-phonegap cordova plugins. Anyway the status bar plugin has helped me achieve fullscreen so I'm happy!

**Comment by neilrackett** [comment]
Glad you found a solution.
