### ISSUE TITLE
override abstract method onWindowStartingActionMode

### ISSUE THREAD

**Issue by jacksonp** [mesmotronic/cordova-plugin-fullscreen#13]
Hi, I get the following error with this recent release: http://cordova.apache.org/announcements/2015/11/09/cordova-android-5.0.0.html

platforms/android/src/com/mesmotronic/plugins/FullScreenPlugin.java:360: error: <anonymous com.mesmotronic.plugins.FullScreenPlugin$6$3> is not abstract and does not override abstract method onWindowStartingActionMode(android.view.ActionMode.Callback,int) in android.view.Window.Callback

Maybe to do with the bump to API level 23?

**Comment by neilrackett** [comment]
Looks like there's a couple of new overloads added to the method list in API 23, should have a fix pushed shortly.
