### ISSUE TITLE
BackButton

### ISSUE THREAD

**Issue by boredom2** [mesmotronic/cordova-plugin-fullscreen#15]
Hi there,

thnaks for your excellent Plugin. I just noticed, that the "Backbutton" is not working anymore, once the App is in Immersive Mode. I know, that it once worked without any Issues, but since a while, it seems to stop working.
Are you aware of that and/or have a solution for this?
(android 6.0.1 on a nexus 6p with latest Cordova (5.4.1))

Thanks a lot!

**Comment by neilrackett** [comment]
It looks like there might be an issue with `dispatchKeyEvent`not being passed through correctly: should have a fix ready soon (ish)
