### ISSUE TITLE
Android 4.4.4 - should I use latest plugin version?

### ISSUE THREAD

**Issue by DenisBiondic** [mesmotronic/cordova-plugin-fullscreen#18]
Hi,

I remember from the readme.md file there was a line like this:
**IMPORTANT:** If you are targeting API <= 22 you should continue using version 1.0.2.

Since it was removed, does this mean it is "safe" to use latest version for overall development which targets both API<22 and API >= 22 ?

**Comment by neilrackett** [comment]
*Yes*, release 1.1.0 should work happily with API 22.
