### ISSUE TITLE
showUnderStatusBar (translucent) is not affected until input is focused (keyboard forces to resize the window)

### ISSUE THREAD

**Issue by lain-me** [mesmotronic/cordova-plugin-fullscreen#20]
showUnderStatusBar should call                  `window.setFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS, WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
`
which makes the status bar translucent and goes above navbar.

Unfortunately, it does not take effect until I focus some input on android device. After this my window resizes and navbar moves up, behind the status bar, status bar becomes translucent. 

I thought it could be that after setting the flags we need to refresh the view, and tried to make decorView.invalidate() in order to force android to redraw everything, but it seems not working.

Does anyone knows what to do?

https://github.com/lain-me/cordova-plugin-fullscreen/commit/92cb320cb4f751b88105531adaae7b521066192f
https://github.com/lain-me/cordova-plugin-fullscreen/commit/f136f201b3f37cf4c8f506becedb2c2b6968eb7d

**Comment by SrajanPathak** [comment]
I'm also getting the same issue. ..apart from focusing on input field window also resize on when video start streaming.

**Comment by daemswibowo** [comment]
i'm having the same issue too. Any idea ?

**Comment by adil-Pathan** [comment]
First remove android platform, then update android sdk to 26. After that add android platform again. Now it works.

**Comment by pcsantana** [comment]
Hi!
I'm facing the same problem! Any workaround?
I tried to do what @adil-Pathan said, but no success.

Thank you.

**Comment by pcsantana** [comment]
I found a workaround. I posted [here](https://github.com/jeneser/ionic-super-bar/issues/18#issuecomment-452002955)!

I hope it help someone!
Thanks

**Comment by neilrackett** [comment]
This should be resolved in release 1.3.0, if not please feel free to reopen this issue.
