### ISSUE TITLE
isSupported function needs callbacks

### ISSUE THREAD

**Issue by pyblendnet-js** [mesmotronic/cordova-plugin-fullscreen#21]
The readme documentation had seemed to indicate that isSupported() would return a boolean but I could only make it work with success and failure callbacks i.e. isSupported(success, failure) - this was tested to work with IntelXDK in Debug mode on Android 5.0 - maybe the intel xdk version of the plugin is different?

**Comment by neilrackett** [comment]
You are correct: it was originally intended to return a Boolean, but it actually uses callbacks.

Docs updated on GitHub, will be updated on NPM with the next release.
