### ISSUE TITLE
Error loading cordova-browser

### ISSUE THREAD

**Issue by ScottBeeson** [mesmotronic/cordova-plugin-fullscreen#24]
When I run `cordova plugin add cordova-plugin-fullscreen` I get the following output:

> Fetching plugin "cordova-plugin-fullscreen" via npm
> Installing "cordova-plugin-fullscreen" for android
> ANDROID_HOME=d:\sdk\android
> JAVA_HOME=C:\Program Files\Java\jdk1.8.0_131
> Subproject Path: CordovaLib
> Incremental java compilation is an incubating feature.
> :clean
> :CordovaLib:clean
> 
> BUILD SUCCESSFUL
> 
> Total time: 1.427 secs
> Installing "cordova-plugin-fullscreen" for browser
> Error loading cordova-browser

Should I be worried about this?

**Comment by neilrackett** [comment]
No: assuming you can still test your project in the browser without any errors, it's not something you need to worry about.
