### ISSUE TITLE
Error: Module cordova-plugin-fullscreen.AndroidFullScreen does not exist

### ISSUE THREAD

**Issue by igorPhelype** [mesmotronic/cordova-plugin-fullscreen#27]
What could make this error happen?

**Comment by neilrackett** [comment]
The only time I've seen something similar was when we tried to build a project which declared the plugins, but they weren't actually installed for whatever reason.

Try installing the plugin again, or remove and re-add it if Cordova complains.

**Comment by igorPhelype** [comment]
Still complains.
```
    document.addEventListener("deviceready",` onDeviceReady, false);
    function onDeviceReady() {
        // fullScreen configuration
        if(window.device.platform === 'android') {
            // if (window.StatusBar){
            //     window.StatusBar.hide();
            // }
            AndroidFullScreen.immersiveMode();
        } 
        if(window.device.platform === 'ios') {
            statusbar.hide()
        }
    }
```

**Comment by neilrackett** [comment]
If you're still having issues, you should be able to achieve the same outcome using the `Fullscreen` config preference:

```<preference name="Fullscreen" value="true" />```

**Comment by igorPhelype** [comment]
Output in rollbar
```
Error: Module cordova-plugin-statusbar.statusbar does not exist.
1 File "file:///android_asset/www/cordova.js" line 1469 col 15 in addEntry
2 File "file:///android_asset/www/cordova.js" line 1479 col 5 in Object.exports.clobbers
3 File "file:///android_asset/www/cordova.js" line 1893 col 30 in onScriptLoadingComplete
4 File "file:///android_asset/www/cordova.js" line 1926 col 13 in scriptLoadedCallback
5 File "file:///android_asset/www/cordova.js" line 1880 col 17 in HTMLScriptElement.<anonymous>
```

I will try to uninstall this plugin and then use the preference tag

**Comment by igorPhelype** [comment]
I will try it

**Comment by igorPhelype** [comment]
I deleted the plugin, and just add "<preference name="Fullscreen" value="true" />" and the app is now full screen and the error is not displayed anymore, apparently. If it appears again, i will reopen this issue.
