### ISSUE TITLE
Documentation lack?

### ISSUE THREAD

**Issue by brunoMachado92** [mesmotronic/cordova-plugin-fullscreen#28]
Hey, just implemented this plugin. But, i saw that this function 
**// Is this plugin supported?
AndroidFullScreen.isSupported(supportedFunction, errorFunction);**

For success callback has **supportedFunction**

Shouldn't this be **successFunction** ?

Nice plugin!

Regards

**Comment by neilrackett** [comment]
Good spot: yes it should, cheers!
