### ISSUE TITLE
Show System UI doenst work when in Lean Mode

### ISSUE THREAD

**Issue by brunoMachado92** [mesmotronic/cordova-plugin-fullscreen#29]
Hey there,

When in lean mode **(leanMode function),** if i try to Show the UI using the **showSystemUI** function, it behaves in the same way.

If i set it to immersive and after that try to use  **showSystemUI** it works.

How can i fix this?

Thank you!

**Comment by cloudedots-jitendra-dhadavi** [comment]
Show System UI doenst work when in Lean Mode

**Comment by neilrackett** [comment]
This should be resolved in the latest release.
