### ISSUE TITLE
Problems with Android 8 & 9.0?

### ISSUE THREAD

**Issue by hudr** [mesmotronic/cordova-plugin-fullscreen#34]
Actually I have an app with ionic and fullscreen-plugin.
My android version is 7.0 Moto G5 and it works fine.
In other devices with Android 8.0 and 9.0 the plugin isn't work properly.

Other problem I'm having too is about minimize the app and reopen it again.
In this momment the leanMode isnt't working because the bars don't hide anymore.

Is there any bug with these versions? Thanks by the way.

**Comment by hudsonr2018** [comment]
Thanks for the reply. I'm trying to use 25 & 27.
I solved the problem just putting these configs in xml:
    <preference name="Fullscreen" value="true" />
    <preference name="AndroidLaunchMode" value="singleInstance" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="KeepRunning" value="true" />

I don't know if this is the best way but it works.
Thanks again and let me know if I'm doing anything wrong.

**Comment by neilrackett** [comment]
Glad you found a solution.

With the minimum target SDK now 29 for Google Play, I'm closing this issue as you stated it only affects 25 & 27.
