### ISSUE TITLE
disable leanMode

### ISSUE THREAD

**Issue by josephlodero** [mesmotronic/cordova-plugin-fullscreen#37]
is there a way to disable leanMode? 
what im trying to do is when a user full screen the video it will enable the leanmode then if not full screen disable leanmode

thanks!

**Comment by neilrackett** [comment]
Lean mode is designed only to persist until the next user interaction, so my suggestion would be to use immersive mode instead, for example:

```javascript
// When your app enters full screen
AndroidFullScreen.immersiveMode();

// When your app leaves full screen
AndroidFullScreen.showSystemUI();
```
