### ISSUE TITLE
Borderless/notch devices doesn't display a fully fullscreen mode

### ISSUE THREAD

**Issue by Faksprod** [mesmotronic/cordova-plugin-fullscreen#38]
Hello, thanks for this plugin.
I'm not sure where I should open this issue so I first try here. (Should I ask this question on [Cordova Github](https://github.com/apache/cordova) or [Cordova Android Github](https://github.com/apache/cordova-android/)?)

**Infos:**
- Cordova 9.0.1
- Android 8.1.0
- Fullscreen plugin 1.2.0

**Problem:**
The fullscreen mode doesn't works on new very wide and borderless devices such as Samsung Galaxy s10, Google Pixel 3XL or OnePlus 6T. As you can see on the attached file, the app is disturbed/displaced from the top which is displaying a black area.

![android-bordeless-fullscreen-ultrawide](https://user-images.githubusercontent.com/21133515/65510499-5fe8bf80-ded5-11e9-9230-3c8b3059f577.png)

**What should be expected:**
The app webview should be displayed correctly, 100% fullscreen, without that black area.

**Temporary fix:**
I found some help on [StackOverflow](https://stackoverflow.com/a/54369068/2908227) about how to fix this issue. It's a bit tricky. But this solution isn't clean enough, it solves the fullscreen problem but causes other problems such as (see attached file):
- the Status Bar can't be hiding during app launch.
- the Splaschreen can't appears fullscreen (there is still an empty area on left side whatever the width size you give to your image).

![android-theme-full](https://user-images.githubusercontent.com/21133515/65511395-6a0bbd80-ded7-11e9-935a-67b4ce0adb80.png)

Anyone with same problem? Any advises to give about how to use 100% fullscreen on borderless devices? Thanks!

**Comment by neilrackett** [comment]
Try this:

```xml
<config-file parent="/manifest/application" target="AndroidManifest.xml">
    <meta-data android:name="android.max_aspect" android:value="2.16" />
</config-file>
```

I've closed this issue because, from your description, it appears to be a wider Cordova issue rather than a plugin issue.

**Comment by Faksprod** [comment]
Doesn't works either.
Ok, I'm going to open an issue on the Cordova Github. Thanks for your time.
