### ISSUE TITLE
Remove at the bottom

### ISSUE THREAD

**Issue by bymagnum** [mesmotronic/cordova-plugin-fullscreen#42]
Hello!

It's been almost a week, I can't figure out how to remove the full-screen mode at the bottom of the device Honor 8x (most likely somewhere else there is this problem, maybe Samsung... some models) - here is such a band is saved in any mode, it is not possible to remove it in any way...

It suggests that I switch to full-screen display, I assumed that the problem is the difference between the screens and the application, but when trying to install all attempts are exhausted... what can I do? the plugin also doesn't help

Android 10 
EMUI 10.0.0

![alt text](https://i.ibb.co/CpyZ1Q7/photo-2020-08-30-00-44-00.jpg)

**Comment by neilrackett** [comment]
You need to add the following to the `application` element of your Android manifest:

```xml
<meta-data android:name="android.max_aspect" android:value="2.16" />
```

This will let the system know that your app supports very wide screen ratios (default is 1.86); there's more info [in this Google blog post](https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html) for more info.

I'll add this to the documentation and investigate whether it's possible/desirable for the plugin to handle this manifest addition in a future release.

**Comment by neilrackett** [comment]
`max_aspect` is now automatically set to `2.16` by the plugin in release 1.3+
