### ISSUE TITLE
Merge into cordova statusbar plugin

### ISSUE THREAD

**Issue by mobidev111** [mesmotronic/cordova-plugin-fullscreen#6]
Nice work. 

The functionality of this plugin should be part of the cordova statusbar plugin - which hides the statusbar on multiple platforms, including android: https://github.com/apache/cordova-plugin-statusbar/blob/master/src/android/StatusBar.java

This would give code significantly more leverage.

Created a corresponding issue for Cordova: https://issues.apache.org/jira/browse/CB-9131

**Comment by neilrackett** [comment]
The latest official status bar plugin now supports immersive mode, which was the original aim of this plugin, so I'll consider this issue closed.
