### ISSUE TITLE
Immsersive mode not working for certain devices

### ISSUE THREAD

**Issue by dokterbob** [mesmotronic/cordova-plugin-fullscreen#9]
Specifically, we have found the immersive mode to report as non-supported on Xperia Z3 (compact) and Nexus 7. Hope to give more details soon.

**Comment by neilrackett** [comment]
Updating to `android@5.0.0` and adding `<preference name="Fullscreen" value="true" />` in `config.xml` will now put your app into immersive mode, even without this plugin.
